/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Model parameters resident in the TA (Normal World never sees these
 * at runtime for TinyML/QAI). Regenerated by tools/train_*.py.
 */
#ifndef QAI_MODEL_PARAMS_H
#define QAI_MODEL_PARAMS_H

#include <stdint.h>
#include <qai_ta.h>

/* Phase 2–4 baseline: identity weights → score([10,20,-5,3]) = 28 */
static const int32_t qai_baseline_w[QAI_FEATURE_COUNT] = { 1, 1, 1, 1 };
static const int32_t qai_baseline_bias = 0;
static const int32_t qai_baseline_threshold = 0;

/*
 * Phase 5 TinyML: logistic regression in milli-units (QAI_FP_SCALE).
 * Trained offline on a synthetic 4-feature binary dataset.
 * score = (w·x + b) / QAI_FP_SCALE; predict 1 if score > 0.
 */
static const int32_t qai_tinyml_w[QAI_FEATURE_COUNT] = {
	441, 775, -300, 232
};
static const int32_t qai_tinyml_bias = 12;
static const int32_t qai_tinyml_threshold = 0;

/*
 * Phase 6 quantum-inspired hybrid:
 *   score = bias + Σ θ_i x_i + Σ γ_i x_i x_{i+1}
 * Compact θ/γ extracted from a host-side hybrid simulation.
 */
static const int32_t qai_theta[QAI_FEATURE_COUNT] = {
	99, 146, -64, 47
};
static const int32_t qai_gamma[QAI_FEATURE_COUNT] = {
	5, -2, 2, 0
};
static const int32_t qai_qai_bias = -1;
static const int32_t qai_qai_threshold = 0;

/*
 * Phase 8: TA-resident XOR key for protected feature path.
 * Prototype only — replace with TEE secure storage / derived key later.
 */
static const uint8_t qai_prot_key[QAI_PROT_KEY_LEN] = {
	0x51, 0x41, 0x49, 0x2d, 0x4f, 0x50, 0x54, 0x45,
	0x45, 0x2d, 0x50, 0x49, 0x35, 0x2d, 0x4b, 0x31
};

#endif /* QAI_MODEL_PARAMS_H */
